version: "3.8"

services:
  # Postgres services
  postgres:
    image: danieleguiluz44/payroll-postgres
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - backend-network
  # Frontend services
  frontend1:
    image: danieleguiluz44/payroll-frontend
    networks:
      - frontend-network

  frontend2:
    image: danieleguiluz44/payroll-frontend
    networks:
      - frontend-network

  frontend3:
    image: danieleguiluz44/payroll-frontend
    networks:
      - frontend-network

  # Backend services
  backend1:
    image: danieleguiluz44/payroll-backend
    environment:
      - DB_HOST=192.168.1.88
    networks:
      - backend-network

  backend2:
    image: danieleguiluz44/payroll-backend
    environment:
      - DB_HOST=192.168.1.88
    networks:
      - backend-network

  backend3:
    image: danieleguiluz44/payroll-backend:latest
    environment:
      - DB_HOST=192.168.1.88
    networks:
      - backend-network

  # Nginx for frontend load balancing
  nginx-frontend:
    image: nginx:latest
    ports:
      - "8070:80"
    volumes:
      - ./nginx-frontend.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend1
      - frontend2
      - frontend3
    networks:
      - frontend-network

  # Nginx for backend load balancing
  nginx-backend:
    image: nginx:latest
    ports:
      - "8090:8090"
    volumes:
      - ./nginx-backend.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2
      - backend3
    networks:
      - backend-network

networks:
  frontend-network:
  backend-network: